### ============================================= ПОЛЬЗОВАТЕЛИ ===================================================

### Регистрация пользователя
POST http://localhost:3330/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@asd.com",
  "firstName": "Qwe",
  "lastName": "Asd",
  "password": "123456"
}
### Получение детальной информации по id
GET http://localhost:3330/api/auth/16a7ab7d-8e95-40c5-84f5-8c00c170a16b HTTP/1.1

### Авторизация
POST http://localhost:3330/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@asd.com",
  "password": "123456"
}

### =============================================== ПУБЛИКАЦИИ ===================================================

### Запрос публикаций
GET http://localhost:3331/api/posts HTTP/1.1

### Запрос публикаций (пагинация)
GET http://localhost:3331/api/posts?page=3&postsCount=3 HTTP/1.1

### Запрос с параметром authorId
GET http://localhost:3331/api/posts?postsCount=10&authorId=3afa868f-e0d7-450d-bef5-101667e6b888 HTTP/1.1

### Запрос с параметром tag
GET http://localhost:3331/api/posts?postsCount=5&tag=ert HTTP/1.1

### Редактирование публикации
PATCH http://localhost:3331/api/posts/1669567308124 HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "content": {
    "title": "",
    "announcement": "",
    "text": ""
  },
  "tags": ["qwe", "ert", "zxc"],
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b836"
}

### Удаление публикации
DELETE http://localhost:3331/api/posts/1669567228439 HTTP/1.1

### Лайк
PATCH http://localhost:3331/api/posts/1669567228439/like HTTP/1.1
Content-Type: application/json

{
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b888"
}

### Репост публикации
POST http://localhost:3331/api/posts/repost/1669567100182 HTTP/1.1
Content-Type: application/json

{
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b777"
}

### Создание публикации типа video
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "isPublished": true,
  "content": {
    "title": "Chill Music Lab",
    "url": "https://www.youtube.com/watch?v=Q7t4JOt-KH4"
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b836"
}

### Создание публикации типа text
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "isPublished": true,
  "content": {
    "title": "",
    "announcement": "",
    "text": ""
  },
  "tags": ["qwe", "ert", "zxc"],
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b888"
}

### Создание публикации типа quote
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "quote",
  "isPublished": true,
  "content": {
    "text": "",
    "author": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b836"
}

### Создание публикации типа photo
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "photo",
  "content": {
    "image": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b836"
}

### Создание публикации типа link
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "link",
  "content": {
    "url": "",
    "description": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "3afa868f-e0d7-450d-bef5-101667e6b836"
}

### =============================================== КОММЕНТАРИИ ==================================================

### Добавление комментария
POST http://localhost:3331/api/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Comment text",
  "postId": 1669391408573,
  "userId": "16a7ab7d-8e95-40c5-84f5-8c00c170a16b"
}

### Получение комментариев к публикации
GET http://localhost:3331/api/comments/1669391408573 HTTP/1.1

### Получение комментариев к публикации (пагинация)
GET http://localhost:3331/api/comments/1669391408573?page=2&commentsCount=3 HTTP/1.1

### Получение комментариев к публикации с параметром commentsCount
GET http://localhost:3331/api/comments/1669204984155?commentsCount=2 HTTP/1.1

### Удаление комментария
DELETE http://localhost:3331/api/comments/1669567573643 HTTP/1.1
