### ============================================= ПОЛЬЗОВАТЕЛИ ===================================================

### Регистрация пользователя
POST http://localhost:3330/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "mikhail@sakharov.com",
  "firstName": "mikhail",
  "lastName": "sakharov",
  "password": "123456"
}
### Получение детальной информации по id
GET http://localhost:3330/api/auth/6398ab2b5a6c4e3fefe83771 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Mzk4YWIyYjVhNmM0ZTNmZWZlODM3NzEiLCJlbWFpbCI6InF3ZUBhc2QuY29tIiwiZmlyc3RuYW1lIjoiUXdlIiwibGFzdG5hbWUiOiJBc2QiLCJpYXQiOjE2NzE0NjgxNTUsImV4cCI6MTY3MTQ2ODIxNX0.gBRrUTowSP0s19OqNmCzyk3h6F0sWeSFKwj-UAM7uBo

### Авторизация
POST http://localhost:3330/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "mikhail@sakharov.com",
  "password": "123456"
}

### Подписка на пользователя
POST http://localhost:3330/api/auth/63c0643ea074395b7d391c82/subscribe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2MwNjQzZWEwNzQzOTViN2QzOTFjODIiLCJlbWFpbCI6Im1pa2hhaWxAc2FraGFyb3YuY29tIiwiZmlyc3RuYW1lIjoibWlraGFpbCIsImxhc3RuYW1lIjoic2FraGFyb3YiLCJpYXQiOjE2NzM1NTMxMDMsImV4cCI6MTY3MzU1MzE2M30.ODBNlXhBsaSBvIa7emFjfok3GeTxgaDZhtefchTJsFY

### =============================================== ПУБЛИКАЦИИ ===================================================

### Запрос публикаций
GET http://localhost:3331/api/posts HTTP/1.1

### Запрос с сортировкой по лайкам
GET http://localhost:3331/api/posts?sortType=likes HTTP/1.1

### Запрос с сортировкой по комментам
GET http://localhost:3331/api/posts?sortType=comments HTTP/1.1

### Запрос публикаций (пагинация)
GET http://localhost:3331/api/posts?page=3&postsCount=3 HTTP/1.1

### Запрос с параметром authorId
GET http://localhost:3331/api/posts?authorId=6398ab2b5a6c4e3fefe83773 HTTP/1.1

### Запрос с параметром tag
GET http://localhost:3331/api/posts?tag=ert HTTP/1.1

### Запрос с параметром type
GET http://localhost:3331/api/posts?type=quote HTTP/1.1

### Редактирование публикации
PATCH http://localhost:3331/api/posts/58 HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "isPublished": true,
  "content": {
    "title": "fgh",
    "announcement": "hjk",
    "text": "vbn"
  },
  "tags": ["ttt", "yyy", "uuiii"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Удаление публикации
DELETE http://localhost:3331/api/posts/59 HTTP/1.1

### Лайк
PATCH http://localhost:3331/api/posts/65/like HTTP/1.1
Content-Type: application/json

{
  "authorId": "6398ae9b5a6c4e3fefe83783"
}

### Репост публикации
POST http://localhost:3331/api/posts/repost/56 HTTP/1.1
Content-Type: application/json

{
  "authorId": "6384f0dca6f361cbc1b80878"
}

### Создание публикации типа video
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "isPublished": true,
  "content": {
    "title": "Chill Music Lab",
    "url": "https://www.youtube.com/watch?v=Q7t4JOt-KH4"
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "63c011443ef866d3e8f67d6c"
}

### Создание публикации типа text
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "isPublished": true,
  "content": {
    "title": "",
    "announcement": "",
    "text": ""
  },
  "tags": ["qwe", "ert", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Создание публикации типа quote
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "quote",
  "isPublished": true,
  "content": {
    "text": "",
    "author": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Создание публикации типа photo
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "photo",
  "content": {
    "image": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### Создание публикации типа link
POST http://localhost:3331/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "link",
  "content": {
    "url": "",
    "description": ""
  },
  "tags": ["qwe", "asd", "zxc"],
  "authorId": "6398ab2b5a6c4e3fefe83771"
}

### =============================================== КОММЕНТАРИИ ==================================================

### Добавление комментария
POST http://localhost:3331/api/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Comment text 2",
  "postId": 64,
  "userId": "6384f4b25b814ae07c87f627"
}

### Получение комментариев к публикации
GET http://localhost:3331/api/comments/58 HTTP/1.1

### Получение комментариев к публикации (пагинация)
GET http://localhost:3331/api/comments/60?page=1&commentsCount=1 HTTP/1.1

### Получение комментариев к публикации с параметром commentsCount
GET http://localhost:3331/api/comments/32?commentsCount=3 HTTP/1.1

### Удаление комментария
DELETE http://localhost:3331/api/comments/12 HTTP/1.1
